source 'https://rubygems.org'

gem 'puppet', '~> 3.7.1', :require => false
gem 'facter', '~> 2.2.0', :require => false

gem 'rspec', '< 3.0.0', :require => false

gem 'puppetlabs_spec_helper', '~> 0.8.1', :require => false
gem 'puppet-lint', '~> 1.0.1', :require => false

gem 'beaker', '~> 1.17.7'
gem 'beaker-rspec', '~> 2.2.6', :require => false
# gem 'serverspec', '~> 0.15.4', :require => false

gem 'pry',                     :require => false
