HOSTS:
  centos-65-x64:
    roles:
      - default
    platform: el-6-x86_64
    box : centos-65-x64-vbox4210-nocm
    box_url : http://puppet-vagrant-boxes.puppetlabs.com/centos-65-x64-vbox4210-nocm.box
    hypervisor : vagrant
CONFIG:
  type: foss
